[package]
name = "init"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Bittman <danielbittman1@gmail.com>"]

[dependencies]
twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-rt-abi = { path = "../../abi/rt-abi" }
twizzler-runtime = { path = "../../rt" }
twizzler-object = { path = "../../lib/twizzler-object" }
twizzler-queue = { path = "../../lib/twizzler-queue" }
rprompt = "1.0.5"
tracing = "0.1"
tracing-subscriber = "0.3.17"
async-io = "2.3.2"
async-executor = "1.9.1"
polling = "3.6.0"
futures = "*"
twizzler-futures = { path = "../../lib/twizzler-futures" }
monitor-api = { path = "../../rt/monitor-api" }
