[package]
name = "foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bar = {path = "../../lib/bar"}
logboi = {path = "../../lib/logboi"}
twz-rt = { path = "../../runtime/twz-rt" }
monitor = { path = "../../runtime/monitor" }
