[package]
name = "devmgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-driver = { path = "../../lib/twizzler-driver" }
twizzler-object = { path = "../../lib/twizzler-object" }
twizzler-abi = { path = "../../lib/twizzler-abi" }
pci-ids = "0.2.4"