[package]
name = "devmgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-driver = { path = "../../lib/twizzler-driver" }
twizzler-object = { path = "../../lib/twizzler-object" }
twizzler-abi = { path = "../../lib/twizzler-abi" }
twizzler-async = { path = "../../lib/twizzler-async" }
twizzler-runtime = { path = "../../runtime/rt" }
pci-ids = "0.2.4"
async-trait = "0.1.56"
#nvme = { path = "../../lib/nvme-rs" }
volatile = "0.5"

#[package.metadata]
#twizzler-build = "static"
