[package]
name = "obliviate-core"
version = "0.1.0"
edition = "2021"

[features]
lethe-caching = []
lethe-interval-tracking = []
lorax-caching = []
lorax-interval-tracking = []
usdb-caching = []

[dependencies]
aes = "0.8.3"
bincode = "1.3.3"
bit-set = "0.5.3"
blake3 = "1.5.1"
clap = { version = "4.2.2", features = ["derive"] }
config = "0.14.0"
crc = "3.0.1"
ctr = "0.9.2"
dashmap = "6.0.1"
env_logger = "0.11.5"

generic-array = { version = "0.14" }
hashbrown = "0.14.5"
hex = "0.4.3"
itertools = "0.12.1"
libc = "0.2.153"
lru = "0.12.3"
lru-mem = { path = "../crates/lru-mem" }
fatfs = { git = "https://github.com/zphrs/rust-fatfs.git", branch = "zphrs-rwproxy", version = "0.4.0", features = [
    "std",
    "log_level_info",
    "lfn",
    "alloc",
], default-features = false }
# naslr = { path = "../crates/naslr" }
num-traits = { version = "0.2.16" }
once_cell = "1.19.0"
paste = "1.0.14"
path_macro = "1.0.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.10.5"
rhexdump = "0.2.0"
ron = "0.8.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_with = "3.6.0"
sha3 = "0.10.8"
thiserror = "1.0.63"
toml = "0.8.16"
tracing = "0.1.40"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
walkdir = "2.5.0"

[dev-dependencies]
anyhow = "1.0.71"
criterion = { version = "0.5.1", features = ["html_reports"] }
crossterm = "0.23"
nom = "7.1.3"
once_cell = "1.19.0"
tui = "0.18.0"
unicode-width = "0.1"
