[package]
name = "gfxtest"
version = "0.1.0"
edition = "2024"

[dependencies]
twizzler = { path = "../../lib/twizzler" }
twizzler-display = { path = "../../lib/twizzler-display" }
secgate = { path = "../../lib/secgate" }
image = "*"
