[package]
name = "monitor-api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-runtime-api = { path = "../../lib/twizzler-runtime-api", default-features = false }
twizzler-abi = { path = "../../lib/twizzler-abi", default-features = false }
secgate = { path = "../secgate" }
dynlink = { path = "../dynlink" }

