[package]
name = "netmgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twizzler-net = {path="../../lib/twizzler-net", features = ["manager"]}
twizzler = {path="../../lib/twizzler"}
twizzler-async = {path = "../../lib/twizzler-async"}
twizzler-abi = {path = "../../lib/twizzler-abi"}
twizzler-queue = {path = "../../lib/twizzler-queue"}