changelog-seen = 2

[install]
prefix = "../../install"
sysconfdir = "etc"

[llvm]
download-ci-llvm = false
targets = "AArch64;X86"
experimental-targets = ""
ninja = true
clang = true

[build]
docs = false
target = []
submodules = false

[rust]
lld = true
llvm-tools = true
debug = true
debuginfo-level = 1
dist-src = false

[dist]
src-tarball = false
